name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  generate:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: rkriswibowo-cloud
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publish Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
